name: DevOps Revision CI

on:
  push:
    branches: [main]

jobs:
  linux-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/Checkout@v3

      - name: Run system info
        uses: bash scrips/system_info.sh

      - name: List files
        run: ls -R .
